config/urls.py
from django.utils.translation import ugettext_lazy as _

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from events.views import (
    # create_form_entry,
    edit_form_entry,
    view_form_entry,
    form_entry_submitted,
    delete_form_entry,
    dashboard,
    add_form_element_entry,
    edit_form_element_entry,
    delete_form_element_entry,
    add_form_handler_entry,
    edit_form_handler_entry,
    delete_form_handler_entry,
    # EventDetailInvitati,
)

urlpatterns = [
    url(r'^$', TemplateView.as_view(
        template_name='pages/home.html'), name='home'),
    # url(r'^about/$', TemplateView.as_view(
    #     template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^api-auth/', include(
        'rest_framework.urls',
        namespace='rest_framework')),

    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),

    # User management
    url(r'^users/', include('project.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^events/', include('events.urls', namespace='events')),

    # API
    url(r'^api/', include('events.api.urls', namespace='api')),

    # url(r'^invitati/(?P<secret>[-\w\d]+)/$',
    #     EventDetailInvitati.as_view(), name='invitati'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),


    # # View URLs
    # url(r'^fobi/', include('fobi.urls.view')),

    # # # Edit URLs
    # # Create form entry
    # url(r'^forms/create/$',
    #     view=create_form_entry,
    #     name='fobi.create_form_entry'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

events/urls.py
from django.conf.urls import include, url
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework_jwt.views import obtain_jwt_token

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.EventList.as_view(),
        name='list'
    ),

    url(r'^api-token-auth/', obtain_jwt_token),
    # url(
    #     regex=r'^(?P<event_slug>[\w_\-]+)/(?P<invitee_uid>\d+)/$',
    #     view=views.InviteeURL.as_view(),
    #     name='invitee-url'
    # ),

    url(
        regex=r'^emails/(?P<pk>\d+)/$',
        view=views.EmailCreate.as_view(),
        name='email-create'
    ),

    url(r'^emails/$', views.upload_csv, name='upload_csv'),
    # url(
    #     regex=r'^emails/export/$',
    #     view=views.export,
    #     name='email-export'
    # ),

    # url(
    #     regex=r'^emails/delete/(?P<pk>\d+)/$',
    #     view=views.EmailDelete.as_view(),
    #     name='email-delete'
    # ),

    url(
        regex=r'^emails/delete/$',
        view=views.delete_post,
        name='email-delete'
    ),

    url(
        regex=r'^create/$',
        view=views.EventCreate.as_view(),
        name='create'
    ),

    url(
        regex=r'^update/(?P<pk>\d+)/$',
        view=views.EventUpdate.as_view(),
        name='update'
    ),

    url(
        regex=r'^delete/(?P<pk>\d+)/$',
        view=views.EventDelete.as_view(),
        name='delete'
    ),

    url(
        regex=r'^location/delete/(?P<pk>\d+)/$',
        view=views.LocationDelete.as_view(),
        name='l-delete'
    ),

    url(
        regex=r'^location/update/(?P<pk>\d+)/$',
        view=views.LocationUpdate.as_view(),
        name='l-update'
    ),

    url(
        regex=r'^(?P<pk>\d+)/$',
        view=views.EventDetail.as_view(),
        name='detail'
    ),

    url(
        regex=r'^(?P<pk>\d+)/location/$',
        view=views.LocationCreate.as_view(),
        name='l-create'
    ),

    # Edit URLs

    # Edit form entry
    url(r'^collections/edit/(?P<form_entry_id>\d+)/$',
        views.edit_form_entry,
        name='fobi.edit_form_entry'),

    # # Edit form entry
    # url(r'^forms/edit/(?P<form_entry_id>\d+)/$',
    #     views.edit_form_entry,
    #     name='fobi.edit_form_entry'),

    # url(r'^snippets/$', api_view.UserEventList.as_view()),
    # url(r'^snippets/(?P<slug>[\w_\-]+)/$', api_view.SnippetDetail.as_view()),


    # View form entry for guests
    url(r'^(?P<secret>[\w_\-]+)/$',
        views.view_form_entry,
        name='fobi.view_form_entry'),

    # View form entry for public
    url(r'^a/(?P<form_entry_slug>[\w_\-]+)/$',
        views.view_form_entry_public,
        name='fobi.view_form_entry_public'),

    # Forms dashboard
    url(r'^collections/$', view=views.dashboard, name='fobi.dashboard'),

    # Delete form entry
    url(r'^collections/delete/(?P<form_entry_id>\d+)/$',
        views.delete_form_entry,
        name='fobi.delete_form_entry'),

    # Add form element entry
    url(r'^collections/elements/add/(?P<form_entry_id>\d+)/'
        r'(?P<form_element_plugin_uid>[\w_\-]+)/$',
        views.add_form_element_entry,
        name='fobi.add_form_element_entry'),

    # Edit form element entry
    url(r'^collections/elements/edit/(?P<form_element_entry_id>\d+)/$',
        views.edit_form_element_entry,
        name='fobi.edit_form_element_entry'),

    # Delete form element entry
    url(r'^collections/elements/delete/(?P<form_element_entry_id>\d+)/$',
        views.delete_form_element_entry,
        name='fobi.delete_form_element_entry'),

    # ***********************************************************************
    # *********************** Form handler entry CUD ************************
    # ***********************************************************************

    # Add form handler entry
    url(r'^collections/handlers/add/(?P<form_entry_id>\d+)/'
        r'(?P<form_handler_plugin_uid>[\w_\-]+)/$',
        views.add_form_handler_entry,
        name='fobi.add_form_handler_entry'),

    # Edit form handler entry
    url(r'^collections/handlers/edit/(?P<form_handler_entry_id>\d+)/$',
        views.edit_form_handler_entry,
        name='fobi.edit_form_handler_entry'),

    # Delete form handler entry
    url(r'^collections/handlers/delete/(?P<form_handler_entry_id>\d+)/$',
        views.delete_form_handler_entry,
        name='fobi.delete_form_handler_entry'),

    # Form submitted success page
    url(r'^view/submitted/$',
        views.form_entry_submitted,
        name='fobi.form_entry_submitted'),

    # Form submitted success page
    url(r'^view/(?P<form_entry_slug>[\w_\-]+)/submitted/$',
        view=views.form_entry_submitted,
        name='fobi.form_entry_submitted'),

    url(r'^collections/plugins/form-handlers/db-store/',
        include('events.contrib.plugins.form_handlers.db_store.urls')),
]

urlpatterns = format_suffix_patterns(urlpatterns)

project/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^~buy-event/$',
        view=views.IncreaseQuota.as_view(),
        name='increase'
    ),
]

project/users/models.py
# Dragos
from django.conf import settings
# end Dragos

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    event_value = models.IntegerField(
        default=settings.DEFAULT_EVENT_VALUES['event'])
    location_value = models.IntegerField(
        default=settings.DEFAULT_EVENT_VALUES['location'])
    collection_value = models.IntegerField(
        default=settings.DEFAULT_EVENT_VALUES['collection'])
    email_value = models.IntegerField(
        default=settings.DEFAULT_EVENT_VALUES['email'])

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

project/users/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.models import Group


class SignupForm(forms.Form):
    first_name = forms.CharField(max_length=30, label='First Name')
    last_name = forms.CharField(max_length=30, label='Last Name')

    def signup(self, request, user):
        role = request.session.get('user_type')
        group = role or "Free"
        g = Group.objects.get(name=group)
        user.groups.add(g)
        user.save()

project/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

# from django_hosts.resolvers import reverse_host
from django_hosts.resolvers import reverse_host_lazy

from .models import User
# from django.conf import settings


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})
        # reverse_host_lazy('users', args=('cici',))


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name',
              'event_value',
              'location_value',
              'collection_value',
              'email_value']

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class IncreaseQuota(LoginRequiredMixin, UpdateView):
    fields = ['event_value', 'location_value']
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)

project/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

project/templates/base.html
{% load staticfiles i18n compress %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}Events Project{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    {% block head_extra %}{% endblock head_extra %}
    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">


    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.4/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css" />
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.4/js/fileinput.min.js"></script>

    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link href="{% static 'css/normalize.css' %}" rel="stylesheet">
    <link href="{% static 'css/demo.css' %}" rel="stylesheet">
    <link href="{% static 'css/set1.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">
    {% endcompress %}
    <script src="https://use.fontawesome.com/b52a206494.js"></script>

<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.16/r-2.2.0/datatables.min.css"/>
 
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.16/r-2.2.0/datatables.min.js"></script>







    {% endblock %}

  </head>

  <body>
    {% if messages %}
      {% for message in messages %}
        <div id="headerBar" class="headerBar {% if messages %}{% for message in messages %}alert {% if message.tags %}alert-{{ message.tags }}{% endif %}{% endfor %}{% endif %}">
          {{ message }}
        </div>
      {% endfor %}
    {% else %}
      <div class="headerBar"></div>
    {% endif %}
    <div class="container">
    <div class="mb-1">
    {% block menu %}
    <nav class="navbar navbar-expand-md navbar-light bg-faded lineUnder">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.resolver_match.url_name == 'create' %}active{% endif %}">
              <a class="nav-link" href="{% url 'events:create' %}">Create New Event <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% if request.resolver_match.url_name == 'list' %}active{% endif %}">
              <a class="nav-link" href="{% url 'events:list' %}">Events</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{# url 'about' request.user.username #}">Settings</a>
              <a class="nav-link" href="{# url 'about' #}">Settings</a>
            </li>
            </ul>
            {% if request.user.is_authenticated %}
              <span class="nav-item" style="border-left: thin solid #7ca5af;">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{{request.user.username}} - Log Out</a>
              </span>
            {% else %}
              <span class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </span>
              <span class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </span>
            {% endif %}
          </ul>
        </div>
    </nav>
    {% endblock menu %}
      </div>
      {# {% if messages %} #}
          {# {% for message in messages %} #}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{# {{ message }} #}</div>
          {# {% endfor %} #}
      {# {% endif %} #}

      {% block content %}
        <p><strong>Use this document as a way to quick start any new project.</strong></p>
        <a href="/">Some colour baby</a>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->



    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}

    {% block js %}
    {% endblock js %}
  </body>
</html>
 

project/templates/base_invitati.html
{% load easy_maps_tags staticfiles %}
{% load crispy_forms_tags fobi_tags %}

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Grayscale - Start Bootstrap Theme</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Cabin:700' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/grayscale.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">{{ event.title }}</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#download">Download</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Intro Header -->
    <header class="masthead" style="background:url({{event.image.url}}) no-repeat bottom center scroll;">
      <div class="intro-body">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 mx-auto">
              <h2 class="brand-heading">{{ event.title }}</h2>
              <span class="intro-text">{{ event.description|truncatechars:450|safe }}</span><br>
              <a href="#about" class="btn btn-circle js-scroll-trigger">
                <i class="fa fa-angle-double-down animated"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- About Section -->
    <section id="about" class="content-section text-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>About Grayscale</h2>
            {{ event.description|safe }}
          </div>
        </div>
      </div>
    </section>

    <!-- Download Section -->
    <section id="download" class="download-section content-section text-center">
      <div class="container">
        <div class="col-lg-8 mx-auto">
          <h2>Locations</h2>
          {% for location in locations %}
            <p>{{ location.l_title }}</p>
            <p>{{ location.location_quota }}</p>
            <p>{{ location.l_date }}</p>
            <p>{{ location.address }}</p>
            <p>{% easy_map location.address %}</p>
          {% endfor %}
          {% for option in form %}
            {% if forloop.first %}
            {% if option %}
            <div class="row" id="options">
                <div class="col-md-12" id="option">
                <hr>
                    {% with option.form as form %}
                        {% include fobi_theme.view_form_entry_ajax_template %}
                    {% endwith %}
                <hr> 

{# {% block form_non_field_and_hidden_errors %} #}
    {# {% get_form_hidden_fields_errors form as form_hidden_fields_errors %} #}
    {# {% if form.non_field_errors or form_hidden_fields_errors %} #}
        {# {% include fobi_theme.form_non_field_and_hidden_errors_snippet_template %} #}
    {# {% endif %} #}
{# {% endblock form_non_field_and_hidden_errors %} #}


                </div>
            </div>
            {% else %}
            {% endif %}
            {% endif %}
        {% endfor %}
        <hr>
           {{das}}
        {# {% crispy collections %} #}
        {# {% crispy form %} #}
        </div>
      </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="content-section text-center">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h2>Contact Start Bootstrap</h2>
            <p>Feel free to leave us a comment on the
              <a href="http://startbootstrap.com/template-overviews/grayscale/">Grayscale template overview page</a>
              on Start Bootstrap to give some feedback about this theme!</p>
            <ul class="list-inline banner-social-buttons">
              <li class="list-inline-item">
                <a href="https://twitter.com/SBootstrap" class="btn btn-default btn-lg">
                  <i class="fa fa-twitter fa-fw"></i>
                  <span class="network-name">Twitter</span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://github.com/BlackrockDigital/startbootstrap" class="btn btn-default btn-lg">
                  <i class="fa fa-github fa-fw"></i>
                  <span class="network-name">Github</span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="https://plus.google.com/+Startbootstrap/posts" class="btn btn-default btn-lg">
                  <i class="fa fa-google-plus fa-fw"></i>
                  <span class="network-name">Google+</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <!-- Map Section -->
    <div id="map"></div>

    <!-- Footer -->
    <footer>
      <div class="container text-center">
        <p>Copyright &copy; Your Website 2017</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCRngKslUGJTlibkQ3FkfTxj3Xss1UlZDA&sensor=false"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/grayscale.min.js' %}"></script>

  </body>

</html>