config/urls.py
from django.utils.translation import ugettext_lazy as _

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from events.views import (
    # create_form_entry,
    edit_form_entry,
    view_form_entry,
    form_entry_submitted,
    delete_form_entry,
    dashboard,
    add_form_element_entry,
    edit_form_element_entry,
    delete_form_element_entry,
    add_form_handler_entry,
    edit_form_handler_entry,
    delete_form_handler_entry,
    # EventDetailInvitati,
)

urlpatterns = [
    url(r'^$', TemplateView.as_view(
        template_name='pages/home.html'), name='home'),
    # url(r'^about/$', TemplateView.as_view(
    #     template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^api-auth/', include(
        'rest_framework.urls',
        namespace='rest_framework')),

    url(r'^rest-auth/', include('rest_auth.urls')),
    url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),

    # User management
    url(r'^users/', include('project.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^events/', include('events.urls', namespace='events')),

    # API
    url(r'^api/', include('events.api.urls', namespace='api')),

    # url(r'^invitati/(?P<secret>[-\w\d]+)/$',
    #     EventDetailInvitati.as_view(), name='invitati'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),


    # # View URLs
    # url(r'^fobi/', include('fobi.urls.view')),

    # # # Edit URLs
    # # Create form entry
    # url(r'^forms/create/$',
    #     view=create_form_entry,
    #     name='fobi.create_form_entry'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

events/urls.py
from django.conf.urls import include, url
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework_jwt.views import obtain_jwt_token

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.EventList.as_view(),
        name='list'
    ),

    url(r'^api-token-auth/', obtain_jwt_token),
    # url(
    #     regex=r'^(?P<event_slug>[\w_\-]+)/(?P<invitee_uid>\d+)/$',
    #     view=views.InviteeURL.as_view(),
    #     name='invitee-url'
    # ),

    url(
        regex=r'^emails/(?P<pk>\d+)/$',
        view=views.EmailCreate.as_view(),
        name='email-create'
    ),

    url(r'^emails/$', views.upload_csv, name='upload_csv'),
    # url(
    #     regex=r'^emails/export/$',
    #     view=views.export,
    #     name='email-export'
    # ),

    # url(
    #     regex=r'^emails/delete/(?P<pk>\d+)/$',
    #     view=views.EmailDelete.as_view(),
    #     name='email-delete'
    # ),

    url(
        regex=r'^emails/delete/$',
        view=views.delete_post,
        name='email-delete'
    ),

    url(
        regex=r'^create/$',
        view=views.EventCreate.as_view(),
        name='create'
    ),

    url(
        regex=r'^update/(?P<pk>\d+)/$',
        view=views.EventUpdate.as_view(),
        name='update'
    ),

    url(
        regex=r'^delete/(?P<pk>\d+)/$',
        view=views.EventDelete.as_view(),
        name='delete'
    ),

    url(
        regex=r'^location/delete/(?P<pk>\d+)/$',
        view=views.LocationDelete.as_view(),
        name='l-delete'
    ),

    url(
        regex=r'^location/update/(?P<pk>\d+)/$',
        view=views.LocationUpdate.as_view(),
        name='l-update'
    ),

    url(
        regex=r'^(?P<pk>\d+)/$',
        view=views.EventDetail.as_view(),
        name='detail'
    ),

    url(
        regex=r'^(?P<pk>\d+)/location/$',
        view=views.LocationCreate.as_view(),
        name='l-create'
    ),

    # Edit URLs

    # Edit form entry
    url(r'^collections/edit/(?P<form_entry_id>\d+)/$',
        views.edit_form_entry,
        name='fobi.edit_form_entry'),

    # # Edit form entry
    # url(r'^forms/edit/(?P<form_entry_id>\d+)/$',
    #     views.edit_form_entry,
    #     name='fobi.edit_form_entry'),

    # url(r'^snippets/$', api_view.UserEventList.as_view()),
    # url(r'^snippets/(?P<slug>[\w_\-]+)/$', api_view.SnippetDetail.as_view()),


    # View form entry for guests
    url(r'^(?P<secret>[\w_\-]+)/$',
        views.view_form_entry,
        name='fobi.view_form_entry'),

    # View form entry for public
    url(r'^a/(?P<form_entry_slug>[\w_\-]+)/$',
        views.view_form_entry_public,
        name='fobi.view_form_entry_public'),

    # Forms dashboard
    url(r'^collections/$', view=views.dashboard, name='fobi.dashboard'),

    # Delete form entry
    url(r'^collections/delete/(?P<form_entry_id>\d+)/$',
        views.delete_form_entry,
        name='fobi.delete_form_entry'),

    # Add form element entry
    url(r'^collections/elements/add/(?P<form_entry_id>\d+)/'
        r'(?P<form_element_plugin_uid>[\w_\-]+)/$',
        views.add_form_element_entry,
        name='fobi.add_form_element_entry'),

    # Edit form element entry
    url(r'^collections/elements/edit/(?P<form_element_entry_id>\d+)/$',
        views.edit_form_element_entry,
        name='fobi.edit_form_element_entry'),

    # Delete form element entry
    url(r'^collections/elements/delete/(?P<form_element_entry_id>\d+)/$',
        views.delete_form_element_entry,
        name='fobi.delete_form_element_entry'),

    # ***********************************************************************
    # *********************** Form handler entry CUD ************************
    # ***********************************************************************

    # Add form handler entry
    url(r'^collections/handlers/add/(?P<form_entry_id>\d+)/'
        r'(?P<form_handler_plugin_uid>[\w_\-]+)/$',
        views.add_form_handler_entry,
        name='fobi.add_form_handler_entry'),

    # Edit form handler entry
    url(r'^collections/handlers/edit/(?P<form_handler_entry_id>\d+)/$',
        views.edit_form_handler_entry,
        name='fobi.edit_form_handler_entry'),

    # Delete form handler entry
    url(r'^collections/handlers/delete/(?P<form_handler_entry_id>\d+)/$',
        views.delete_form_handler_entry,
        name='fobi.delete_form_handler_entry'),

    # Form submitted success page
    url(r'^view/submitted/$',
        views.form_entry_submitted,
        name='fobi.form_entry_submitted'),

    # Form submitted success page
    url(r'^view/(?P<form_entry_slug>[\w_\-]+)/submitted/$',
        view=views.form_entry_submitted,
        name='fobi.form_entry_submitted'),

    url(r'^collections/plugins/form-handlers/db-store/',
        include('events.contrib.plugins.form_handlers.db_store.urls')),
]

urlpatterns = format_suffix_patterns(urlpatterns)

project/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^~buy-event/$',
        view=views.IncreaseQuota.as_view(),
        name='increase'
    ),
]

project/users/models.py
# Dragos
from django.conf import settings
# end Dragos

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)
    event_value = models.IntegerField(
        default=settings.DEFAULT_EVENT_VALUES['event'])
    location_value = models.IntegerField(
        default=settings.DEFAULT_EVENT_VALUES['location'])
    collection_value = models.IntegerField(
        default=settings.DEFAULT_EVENT_VALUES['collection'])
    email_value = models.IntegerField(
        default=settings.DEFAULT_EVENT_VALUES['email'])

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

events/contrib/plugins/form_elements/content/content_image/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from fobi.base import BasePluginForm, get_theme
from fobi.helpers import handle_uploaded_file

from .settings import (
    FIT_METHODS_CHOICES,
    DEFAULT_FIT_METHOD,
    DEFAULT_SIZE,
    SIZES,
    IMAGES_UPLOAD_DIR,
)

__title__ = 'fobi.contrib.plugins.form_elements.content.content_image.forms'
__author__ = 'Artur Barseghyan <artur.barseghyan@gmail.com>'
__copyright__ = '2014-2017 Artur Barseghyan'
__license__ = 'GPL 2.0/LGPL 2.1'
__all__ = ('ContentImageForm',)

theme = get_theme(request=None, as_instance=True)


class ContentImageForm(forms.Form, BasePluginForm):
    """Form for ``ContentImagePlugin``."""

    plugin_data_fields = [
        ("file", ""),
        ("alt", ""),
        ("fit_method", DEFAULT_FIT_METHOD),
        ("size", DEFAULT_SIZE),
    ]

    file = forms.ImageField(
        label=_("Image"),
        required=True,
        widget=forms.widgets.ClearableFileInput()
        # attrs={'class': theme.form_element_html_class}
    )
    alt = forms.CharField(
        label=_("Alt text"),
        required=True,
        widget=forms.widgets.TextInput(
            attrs={'class': theme.form_element_html_class}
        )
    )
    fit_method = forms.ChoiceField(
        label=_("Fit method"),
        required=False,
        initial=DEFAULT_FIT_METHOD,
        choices=FIT_METHODS_CHOICES,
        widget=forms.widgets.Select(
            attrs={'class': theme.form_element_html_class}
        )
    )
    size = forms.ChoiceField(
        label=_("Size"),
        required=False,
        initial=DEFAULT_SIZE,
        choices=SIZES,
        widget=forms.widgets.Select(
            attrs={'class': theme.form_element_html_class}
        )
    )

    def save_plugin_data(self, request=None):
        """Saving the plugin data and moving the file."""
        file_path = self.cleaned_data.get('file', None)
        if file_path:
            saved_image = handle_uploaded_file(IMAGES_UPLOAD_DIR, file_path)
            self.cleaned_data['file'] = saved_image

events/contrib/plugins/form_elements/content/content_image_url/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from fobi.base import BasePluginForm, get_theme
# from fobi.widgets import NumberInput

from .settings import (
    FIT_METHODS_CHOICES,
    DEFAULT_FIT_METHOD,
    DEFAULT_SIZE,
    SIZES,
)

__title__ = 'fobi.contrib.plugins.form_elements.content.content_image_url.' \
            'forms'
__author__ = 'Artur Barseghyan <artur.barseghyan@gmail.com>'
__copyright__ = '2014-2017 Artur Barseghyan'
__license__ = 'GPL 2.0/LGPL 2.1'
__all__ = ('ContentImageURLForm',)

theme = get_theme(request=None, as_instance=True)


class ContentImageURLForm(forms.Form, BasePluginForm):
    """Form for ``ContentImageURLPlugin``."""

    plugin_data_fields = [
        ("url", ""),
        ("alt", ""),
        ("fit_method", DEFAULT_FIT_METHOD),
        ("size", DEFAULT_SIZE),
    ]

    url = forms.URLField(
        label=_("URL"),
        required=True,
        widget=forms.widgets.URLInput(
            attrs={'class': theme.form_element_html_class}
        )
    )
    alt = forms.CharField(
        label=_("Alt text"),
        required=True,
        widget=forms.widgets.TextInput(
            attrs={'class': theme.form_element_html_class}
        )
    )
    fit_method = forms.ChoiceField(
        label=_("Fit method"),
        required=False,
        initial=DEFAULT_FIT_METHOD,
        choices=FIT_METHODS_CHOICES,
        widget=forms.widgets.Select(
            attrs={'class': theme.form_element_html_class}
        )
    )
    # width = forms.IntegerField(
    #     label=_("Width"),
    #     required=False,
    #     widget=NumberInput(
    #         attrs={'class': theme.form_element_html_class}
    #     )
    # )
    # height = forms.IntegerField(
    #     label=_("Height"),
    #     required=False,
    #     widget=NumberInput(
    #         attrs={'class': theme.form_element_html_class}
    #     )
    # )
    size = forms.ChoiceField(
        label=_("Size"),
        required=False,
        initial=DEFAULT_SIZE,
        choices=SIZES,
        widget=forms.widgets.Select(
            attrs={'class': theme.form_element_html_class}
        )
    )

events/contrib/plugins/form_elements/content/content_text/forms.py
from django import forms
from django.forms.widgets import Textarea
from django.utils.html import strip_tags
from django.utils.translation import ugettext_lazy as _

from fobi.base import BasePluginForm, get_theme

from .settings import ALLOWED_TAGS, ALLOWED_ATTRIBUTES

try:
    import bleach
    BLEACH_INSTALLED = True
except ImportError as err:
    BLEACH_INSTALLED = False

__title__ = 'fobi.contrib.plugins.form_elements.content.content_text.forms'
__author__ = 'Artur Barseghyan <artur.barseghyan@gmail.com>'
__copyright__ = '2014-2017 Artur Barseghyan'
__license__ = 'GPL 2.0/LGPL 2.1'
__all__ = ('ContentTextForm',)


theme = get_theme(request=None, as_instance=True)


class ContentTextForm(forms.Form, BasePluginForm):
    """Form for ``ContentTextPlugin``."""

    plugin_data_fields = [
        ("text", "")
    ]

    text = forms.CharField(
        label=_("Text"),
        required=True,
        widget=Textarea(attrs={'class': theme.form_element_html_class})
    )

    def clean_text(self):
        """Clean text value."""
        if BLEACH_INSTALLED:
            return bleach.clean(
                text=self.cleaned_data['text'],
                tags=ALLOWED_TAGS,
                attributes=ALLOWED_ATTRIBUTES,
                strip=True,
                strip_comments=True
            )
        else:
            return strip_tags(self.cleaned_data['text'])

events/contrib/plugins/form_elements/content/content_video/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from fobi.base import BasePluginForm, get_theme

from .settings import DEFAULT_SIZE, SIZES

__title__ = 'fobi.contrib.plugins.form_elements.content.content_video.forms'
__author__ = 'Artur Barseghyan <artur.barseghyan@gmail.com>'
__copyright__ = '2014-2017 Artur Barseghyan'
__license__ = 'GPL 2.0/LGPL 2.1'
__all__ = ('ContentVideoForm',)

theme = get_theme(request=None, as_instance=True)


class ContentVideoForm(forms.Form, BasePluginForm):
    """Form for ``ContentVideoPlugin``."""

    plugin_data_fields = [
        ("title", ""),
        ("url", ""),
        ("size", DEFAULT_SIZE),
    ]

    title = forms.CharField(
        label=_("Title"),
        required=True,
        widget=forms.widgets.TextInput(
            attrs={'class': theme.form_element_html_class}
        )
    )
    url = forms.CharField(
        label=_("URL"),
        required=True,
        widget=forms.widgets.TextInput(
            attrs={'class': theme.form_element_html_class}
        )
    )
    size = forms.ChoiceField(
        label=_("Size"),
        required=False,
        initial=DEFAULT_SIZE,
        choices=SIZES,
        widget=forms.widgets.Select(
            attrs={'class': theme.form_element_html_class}
        )
    )

project/templates/events/event_detail.html
{% extends "base.html" %}
{% load easy_maps_tags math fobi_tags %}
{% block content %}

<div class="row" id="event">
    <div class="col-md-12">
            <a href="{% url 'events:update' pk=event.pk %}" type="button" class="btn btn-info">Edit Event</a>
            <a href="{% url 'events:delete' pk=event.pk %}">Delete {{ event.title }}</a>
            <hr>
            <h2>{{ event.title }}</h2>
            {% if event.image %}
                <img src="http://www.aplicat.ie:8000{{event.image.url}}" class="img-fluid" style="height: 250px;">
                <br>
            {% endif %}
            <hr>
            {% if event.description %}
                {{ event.description|safe }}
            {% endif %}
    </div>
</div>
{{location_quota.l_title}}<br>
{{event.location_quota}}
<div class="row" id="locations">

    {% for location in locations %}
        <div class="col-md-{{locations.count|div}}" id="location">
        <hr>
            <p>{{ location.l_title }}</p>
            <p>{{ location.location_quota }}</p>
            <p>{{ location.l_date }}</p>
            <p>{{ location.address }}</p>
            <p>{% easy_map location.address %}</p>
            <hr>
            <a href="{% url 'events:l-update' pk=location.pk %}" type="button" class="btn btn-info">Edit Location</a> 
            <a href="{% url 'events:l-delete' pk=location.pk %}">Delete {{ location.l_title }}</a>
        <hr>
        </div>
    {% endfor %}
</div>
{# {% if locations.count < location_quota %} #}
    <a href="{% url 'events:l-create' pk=event.pk %}" type="button" class="btn btn-info">{% if locations.count == 0 %}Add locations{% else %}Add more locations{% endif %}</a>
{# {% endif %} #}

{% for option in options %}
    {% if forloop.first %}
    {% if option %}
    <div class="row" id="options">
        <div class="col-md-12" id="option">
        <hr>
            {% with option.form as form %}
                {% include fobi_theme.form_edit_snippet_template_name %}
            {% endwith %}
        <hr> 
            {% for ana in collection %}
                <a href="{% url 'events:fobi.edit_form_element_entry' form_element_entry_id=ana.pk %}" type="button" class="btn btn-info">Edit collection</a>
                <a href="{% url 'events:fobi.delete_form_element_entry' form_element_entry_id=ana.pk %}">Delete</a>
            {% endfor %}

        <hr>
        </div>
    </div>
    {% else %}
    {% endif %}
    {% endif %}
{% endfor %}
{% if collection.count < collection_quota %}
    <a href="{% url 'events:fobi.edit_form_entry' form_entry_id=event.pk %}" type="button" class="btn btn-info">Add collection</a>
{% endif %}
{% endblock content %}

project/templates/events/event_detail_invitati.html
{% extends "base_invitati.html" %}
{% load easy_maps_tags math fobi_tags %}

{% block image %}
<img class="bg" src="{{event.image.url}}" style="width: 100%; z-index:0; position: absolute;" />

<div class="row" id="event">
    <div class="col-md-12">
            <h2 style="z-index:100;position:absolute;color:white;">{{ event.title }}</h2>
            <hr>
            {% if event.description %}
             <span style="z-index:100;position: absolute;color: white;">{{ event.description|truncatechars:600|safe }}</span>
            {% endif %}
    </div>
</div>
{% endblock image %}

{% block content %}
<div class="row" id="locations">
    {% for location in locations %}
        <div class="col-md-{{locations.count|div}}" id="location">
        <hr>
            <p>{{ location.l_title }}</p>
            <p>{{ location.l_date }}</p>
            <p>{{ location.address }}</p>
            <p>{% easy_map location.address %}</p>
            <hr>
            <a href="{% url 'events:l-update' pk=location.pk %}" type="button" class="btn btn-info">Edit Location</a> 
            <a href="{% url 'events:l-delete' pk=location.pk %}">Delete {{ location.l_title }}</a>
        <hr>
        </div>
    {% endfor %}
</div>
{% if locations.count < 3 %}
    <a href="{% url 'events:l-create' pk=event.pk %}" type="button" class="btn btn-info">{% if locations.count == 0 %}Add locations{% else %}Add more locations{% endif %}</a>
{% endif %}


{% for option in options %}
{% if option %}
    <div class="row" id="options">
        <div class="col-md-12" id="option">
        <hr>
            {% with option.form as form %}
                    {% include fobi_theme.form_edit_snippet_template_name %}
                  {% endwith %}
            <hr>
           <a href="{% url 'events:fobi.edit_form_entry' form_entry_id=event.pk %}" type="button" class="btn btn-info">Edit Options</a> 
           {% for ana in anas %}

                <a href="{% url 'fobi.delete_form_element_entry' form_element_entry_id=ana.pk %}">Delete</a>
            {% endfor %}

        <hr>
        </div>
    </div>


{% else %}

{% endif %}

{% endfor %}
<a href="{% url 'events:fobi.edit_form_entry' form_entry_id=event.pk %}" type="button" class="btn btn-info">{% if locations.count == 0 %}Add options{% else %}Add more options{% endif %}</a>
{% endblock content %}

project/templates/events/event_list.html
{% extends "base.html" %}
{% load easy_maps_tags math static %}
{# {% load hosts %} #}
{% block content %}
    {% if events.count == 0 %}
        <h3 style="font-weight: 600;">Events</h3>
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.<br>
        Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.</p>
        <a href="{# url 'events:create' #}" type="button" class="btn btn-sim">Create New Event</a>
    {% else %}
        <div class="row" id="event">
            <div class="col-md-12">
                <h3 style="font-weight: 600; color:#f26418;">Events</h3>
                <table class="table table-hover" id="myTable">
                  <thead>
                    <tr>
                      <th>EVENT TITLE</th>
                      <th>EVENT CREATION DATE</th>
                      <th>OPTIONS</th>
                      <th>ACTIONS</th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for event in events %}
                    <tr>
                      <th scope="row"><a href="{% url 'events:detail' pk=event.pk %}" style="color: #000;">{{ event.title }}</a></th>
                      <td>{{event.date_created}}</td>
                      <td>
                        <span >
                          <a data-fancybox data-type="iframe" data-src="{# url 'invitati' pk=event.pk #}" href="javascript:;"><i class="color-actions fa fa-eye" aria-hidden="true"></i> Preview</a>
                        </span>
                      <span class="color-actions"><i class="color-actions fa fa-area-chart" aria-hidden="true" style="margin-left:10px;"></i> Statistics</span>
                      </td>
                      <td>
                        <a href="{% url 'events:update' pk=event.pk %}" style="color: #000;">
                          <i class="color-actions fa fa-pencil" aria-hidden="true"></i>
                        </a>
                        <a href="{% url 'events:delete' pk=event.pk %}" class="color-actions">
                          <i class="fa fa-trash" aria-hidden="true" style="margin-left:10px;"></i>
                        </a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>              
            </div>
        </div>
        {% if events.count < quota %}
            <hr>
            <a href="{% url 'events:create' %}" type="button" class="btn btn-sim">Create an Event!</a>
            <hr>
        {% endif %}
    {% endif %}
    <!--<script src="{% static 'js/sorttable.js' %}"></script>-->


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.25/jquery.fancybox.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.25/jquery.fancybox.min.js"></script>



<script type="text/javascript">
  
$('#myTable').DataTable( {
    // scrollY: 100,
    paging: false
} );

</script>
    
{% endblock content %}

project/templates/events/event_list_archive.html
{% extends "base.html" %}

{% block content %}
    {% for event in events %}
    
        {% if user == event.user %}
            <h3>{{ event.title }}</h3>
            {% if event.image %}
                <img src="{{event.image.url}}" class="img-responsive" style="height: 250px;">
                <br>
            {% endif %}
            {% if event.description %}
                {{ event.description|safe }}
            {% endif %}
            <!-- <a href="{% url 'events:update' slug=event.slug %}" type="button" class="btn btn-info">Edit</a>-->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="edit">Edit</button>
            <a href="{% url 'events:delete' slug=event.slug %}">Delete {{ event.title }}</a>
            <!--<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="delete">Delete {{ event.title }}</button>-->
        {% endif %}

    {% endfor %}

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Update the event</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="post" enctype="multipart/form-data" id="event-form-update" action='{# url "events:list" #}' data-url='{% url "events:list" %}'>
        {% csrf_token %}
            {{ form.media }}
            {{ form.as_p|safe }}
            <input type="submit" class="btn btn-primary" value="Save changes" />
        </form>

            <div id="test">
            </div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
    
    $('#exampleModal').on('show.bs.modal', function (event) {
      var button = $(event.relatedTarget) // Button that triggered the modal
      var recipient = button.data('whatever') // Extract info from data-* attributes
      // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).


      // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
      var modal = $(this)
      modal.find('.modal-title').text('New message to ' + recipient)
      modal.find('.modal-body input').val(recipient)
    })

    $(document).ready(function(){
    var $myForm = $('#event-form-update')
    $myForm.addClass('inactive')
    $myForm.submit(function(event){
        event.preventDefault()
        var $formData = $(this).serialize()
        var $thisURL = $myForm.attr('data-url')
        $.ajax({
            method: "POST",
            url: '/update/o/',
            data: $formData,
            success: handleFormSuccess,
            error: handleFormError,
        })
    })

    function handleFormSuccess(response){
        console.log(response)
        $('#test').append('<h4>Title: '+response.title+'</h4>'+response.description)
        // $('#test').html(response);
    }

    function handleFormError(jqXHR, textStatus, errorThrown){
        console.log(jqXHR)
        console.log(textStatus)
        console.log(errorThrown)
    }
})

</script>
{% endblock content %}